import type { Metadata } from "next";
import {
  Poppins,
  Playfair_Display,
  Kanit,
  Nunito,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";
import UnderBar from "./components/underBar/underBar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const nunito = Nunito({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const playFair = Playfair_Display({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-playFair",
});

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: never;
}>) {
  return (
    <html
      lang="en"
      className={`overflow-hidden ${poppins.variable} ${kanit.variable} ${playFair.variable} ${montserrat.variable}`}
    >
      <Provider session={session}>
        <body
          className={`w-full h-full text-white bg-black-700 overflow-x-hidden ${nunito.className}`}
        >
          <ToastContainer
            autoClose={3000}
            theme="dark"
            position="bottom-center"
          />
          <main className="w-full h-screen">{children}</main>
          <UnderBar />
        </body>
      </Provider>
    </html>
  );
}
